### ISSUE TITLE
Hero / Sidekick Height

### ISSUE THREAD

**Issue by Code47X** [jballands/Business-Casual#6]
The CSS for the hero-unit and sidekick-unit height is missing px after the value which causes it to become an invalid property value.

Ran into same problem with nav bar top/bot padding and nav bar list item left/right padding:
![screen shot 2014-03-30 at 7 37 08 pm](https://cloud.githubusercontent.com/assets/5169367/2563007/ba4daafc-b86c-11e3-8d18-40d06297c0f9.png)

Found a few more occurrences of this problem. Could it be caused by with the way less is compiling the css?

**Comment by jballands** [comment]
From what I understand: this shouldn't affect the operation of Business Casual on the supported browsers (Chrome, Firefox, Safari, and Opera). They should each automatically interpret the value to be in pixels, as you can see here:

![screen shot 2014-04-20 at 9 33 58 am](https://cloud.githubusercontent.com/assets/2644971/2750630/b1242300-c890-11e3-89cd-d24da56c2fb7.png)

Are you experiencing any problems with the way that it is being rendered?

**Comment by Code47X** [comment]
Hmm... maybe the issue is just on my end then. I was using Chrome when I noticed the problem, it was rendering as if no value was input (defaulted to 0 I believe). I'll see if I can find something on my end that's causing it. Thanks for the update!
